server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/bankDb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  flyway:
    enabled: true